### PR TITLE
Update to v3 and support all settings

### PR DESCRIPTION
**Pull request by Moulick**
Hi @mcblair, I updated this action to support `aws-actions/configure-aws-credentials@v3`. Also modified the inputs to support all of the new inputs supported by v3. This is unfortunately breaking with the existing inputs.

### CODE REVIEW

**Comment by Moulick** [comment]
Found some kinks, setting to draft till I fix em

**Comment by Moulick** [comment]
Ok, it's ready now!

**Comment by confiq** [comment]
this is actually not bad PR but it will break current signature. I might need something like this for my needs

**Comment by Moulick** [comment]
@confiq True, this will need to be released as a major version bump

**Comment by morfien101** [comment]
Is this ever going to be merged is would it be better to just fork and publish a new one?
@mcblair What's your feeling for maintaining this, or did you just use it for your own thing?

**Comment by Moulick** [comment]
I am happy to draft/publish/maintain the action in the marketplace if this PR goes nowhere.

**Comment by morfien101** [comment]
@Moulick Since this PR has been open for months I feel like it's safe to say it's worth forking and publishing your own. Can you drop a link here when you have published?

**Comment by Moulick** [comment]
I'll wait for a couple more days in case @mcblair sees this and decides.

In the meantime, you can still use mine as below.


```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Configure AWS credentials 1
    uses: moulick/configure-aws-profile-action@main
    with:
      role-to-assume: arn:aws:iam::123456789123:role/<role-name>
      role-session-name: GithubActions-${{ env.REPO_NAME }}-${{ github.workflow }}-${{ github.run_id }}
      aws-region: ${{ env.AWS_DEFAULT_REGION }}
      profile: ${{ env.<role>_PROFILE }}
      only-profile: true
      whoami: true
  - name: Configure AWS credentials 2
    uses: moulick/configure-aws-profile-action@main
    with:
      role-to-assume: arn:aws:iam::123456789123:role/<another-role-name>
      role-session-name: GithubActions-${{ env.REPO_NAME }}-${{ github.workflow }}-${{ github.run_id }}
      aws-region: ${{ env.AWS_DEFAULT_REGION }}
      profile: ${{ env.<another-role>_PROFILE }}
      only-profile: true
      whoami: true
```

**Comment by Moulick** [comment]
I'll publish my fork as an action in the marketplace over the weekend!

**Comment by Moulick** [comment]
Hey everyone and @confiq, @morfien101, @benjefferies, @thepsc-go, @dogversioning, I have updated the action to v4 and published to marketplace, let me know if there are any issues in using it or problems making it work with any other action. If you want to use with docker container in a separate step, that's also documented how to. https://github.com/marketplace/actions/configure-multiple-aws-roles, give it star on the marketplace and repo as well please :)

**Pull request closed without merging**
